name: Run Scraper and Update JSON

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (you can change this)
  workflow_dispatch:     # Allows manual triggering from the GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated JSON
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data.json
          git commit -m "Update data.json" || echo "No changes to commit"
          git push